name: Unit Test .NET

on:
  push:
    branches: [ main, dev, feature/*, fix/*, release/* ]

  release:
    types: [ published ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Setup dotnet
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          10.0.x
      # dotnet-quality: 'preview' # When using preview versions
        dotnet-quality: 'ga' # General Availability

    # Create Local NuGet Source

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget

      # UnitTest.Data

    - name: Restore UnitTest.Data
      run: dotnet restore ./src/*/UnitTest.Data.csproj

    - name: Build UnitTest.Data
      run: dotnet build ./src/*/UnitTest.Data.csproj --no-restore  -c Release

    - name: Pack UnitTest.Data
      run: dotnet pack ./src/*/UnitTest.Data.csproj --no-restore -o ~/nuget  -c Release

    - name: Restore UnitTest.Data.Tests
      run: dotnet restore ./src/*/UnitTest.Data.Tests.fsproj

    - name: Test UnitTest.Data.Tests
      run: dotnet test ./src/*/UnitTest.Data.Tests.fsproj --no-restore  -c Release

      # Push

    - name: Push Packages
      if: ${{ github.event_name == 'release' }}
      run: >
        dotnet nuget push "../../../nuget/*.nupkg"
        -s https://api.nuget.org/v3/index.json
        -k ${{ secrets.NuGetSourcePassword }}
        --skip-duplicate
